### ISSUE TITLE
Histogram and BW preview

### ISSUE THREAD

**Issue by MoBe80** [luspi/photoqt-legacy#48]
Hi,
thanks for this nice pice of software. I would like to suggest two features...
1. It would be great to have an histogram in the detailswindow or as an half transparent overlay.
2. A quick Black & White preview mode. 

I do advertising for you!
THX Mo

**Comment by luspi** [comment]
Hi @MoBe80 

Thanks for your suggestions!
I agree, a histogram would be pretty cool to have! Probably after I finished porting PhotoQt to QML (see: https://github.com/luspi/photoqt-qml-dev), I'll try to add that.
Hm, a BW preview for a quick sneak... Well, I'll have to think about that one, as I'm not sure it it actually would be that much faster (as I still need the same image information as for the normal (coloured) images). I'll see what I can find!

Regards
Lukas

**Comment by luspi** [comment]
PhotoQt is moving away from GitHub to GitLab ([more info](http://photoqt.org/news/1434375887)). This issue is duplicated here: https://gitlab.com/luspi/photoqt-legacy/issues

**Comment by luspi** [comment]
I'll close this issue here now as everything is now happening at gitlab for quite some time.

However, before doing this a quick update:
1) Histograms are already available in the current version
2) A quick preview (though not black and white) will be available in the open file element of the coming version

Thanks,
Lukas
